### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by NotTimIsReal**
helps with flexibility and allows for later fixes,

### CODE REVIEW

**Comment by TheUntraceable** [comment]
I don't even think the DockerFile works, let me test it

**Comment by TheUntraceable** [comment]
> I don't even think the DockerFile works, let me test it

That's regarding the one made by me

**Comment by NotTimIsReal** [comment]
> I don't even think the DockerFile works, let me test it

it doesn't doesn't have a source

**Comment by NotTimIsReal** [comment]
did a re-edit and made it clone first

**Comment by TheUntraceable** [comment]
You don't run the bot within the Dockerfile so it won't work

**Comment by NotTimIsReal** [comment]
> You don't run the bot within the Dockerfile so it won't work

You need a .env only so that's why I used ubuntu

**Comment by NotTimIsReal** [comment]
> > You don't run the bot within the Dockerfile so it won't work
> 
> You need a .env only so that's why I used ubuntu

or the file that is required for the secrets

**Comment by TheUntraceable** [comment]
I mean that you're only downloading the code, you're not running the bot

**Comment by TheUntraceable** [comment]
And you're gonna need a config.json in the "Bot Files" dir

**Comment by NotTimIsReal** [comment]
> And you're gonna need a config.json in the "Bot Files" dir

make an example one

**Comment by NotTimIsReal** [comment]
that's your homework

**Comment by TheUntraceable** [comment]
I did.

**Comment by TheUntraceable** [comment]
image

**Comment by NotTimIsReal** [comment]
> image

hm, now we need to do something I call manual editing

**Comment by NotTimIsReal** [comment]
actually make this repo a template

**Comment by TheUntraceable** [comment]
I got an idea, a bash script asking for input?

**Comment by NotTimIsReal** [comment]
> I got an idea, a bash script asking for input?

mm I'll never get that

**Comment by TheUntraceable** [comment]
Forgot you can add environment variables to Dockerfiles, how about I switch to using those?

**Comment by NotTimIsReal** [comment]
> Forgot you can add environment variables to Dockerfiles, how about I switch to using those?

yes but making people remember

**Comment by TheUntraceable** [comment]
We could go back to using the bash script to grab the input and add the flags to the run process I guess...

**Comment by TheUntraceable** [comment]
> > I got an idea, a bash script asking for input?
> 
> mm I'll never get that

What'd you mean you'll never get it?

**Comment by TheUntraceable** [comment]
I could add OS Specific release of the script

**Comment by TheUntraceable** [comment]
Linux/Unix/Posix or whatever it is you call them: Bash, I can do this
Windows: Powershell, I can do this too probably
Can't think of any other OS

**Comment by NotTimIsReal** [comment]
> > > I got an idea, a bash script asking for input?
> > 
> > 
> > mm I'll never get that
> 
> What'd you mean you'll never get it?

accomplish

**Comment by TheUntraceable** [comment]
> > > > I got an idea, a bash script asking for input?
> > > 
> > > 
> > > mm I'll never get that
> > 
> > 
> > What'd you mean you'll never get it?
> 
> accomplish

I'll do it dw

**Comment by NotTimIsReal** [comment]
time to learn bash

**Comment by TheUntraceable** [comment]
> time to learn bash

If you really want I can do it, I already have thought of parts of the script. I'm in school so I'll do it once I'm back in around 6 hours.

**Comment by TheUntraceable** [comment]
> In around 6 hours
And 6 months later is has been. I'll do this because I figured it out.

**Pull request closed without merging**
