### PR TITLE
Make EpikHost invite link correct & Link to commands page in footer

### PR DESCRIPTION
**Pull request by uh-Sid**

### CODE REVIEW

**Comment by TheUntraceable** [comment]
I think that it'd be safer if you used the epikhost vanity, `dsc.gg/epikhost` that I made incase that the url is changed at a later date and so we don't have to do it all over again, just add that and I'll merge, thanks for the pr :D

**Comment by uh-Sid** [comment]
ok, will do

**Comment by uh-Sid** [comment]
done @TheUntraceable

**Comment by TheUntraceable** [comment]
Thanks for the commit!

**Pull request merged**
